# Generated by Django 4.2.4 on 2023-08-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        )
    ]
